version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: nym-ashigaru-terminal_web_1
      APP_PORT: 7682
  
  web:
    image: ghcr.io/thenymman/ashi-t:1.0.0@sha256:0d9edf79ad579f1a64a927312cb290b31da9621290d1ecf69a3e445b9ab8781f
    restart: on-failure
    stop_grace_period: 1m
